### ISSUE TITLE
How to get a python table to autoload?

### ISSUE THREAD

**Issue by cneerdaels** [osquery/osquery-python#22]
I've managed to create a table in python and manually load it so that I can query it via osqueryi, but I can't figure out how to make that table autoload. I feel like I must be missing something obvious, but I'd appreciate any help.

**Comment by marpaia** [comment]
Hey @cneerdaels, have you checked out the [wiki on autoloading extensions](https://osquery.readthedocs.io/en/stable/deployment/extensions/#autoloading-extensions)? Basically, if you have your table set up in a python file (with a shebang at the top and the file marked as executable), you can set an autoload file which points to the python extension and your extension should be auto-loaded.

**Comment by theopolis** [comment]
There's one gotcha, you'll need to name the python file with a `.ext` (you should see a log line if otherwise). ;)

**Comment by cneerdaels** [comment]
Thanks - that advice confirmed was doing things correctly - but also made me realize I was suffering from  an env issue - it was loading the wrong python lib. Got it working now - thanks!
