### ISSUE TITLE
No longer in beta mode?

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery-python#26]
I was able to install this library with pip. Should we remove the comment in the README file?

**Comment by marpaia** [comment]
Speaking of pip and README updates, we could also update the README to be in rst. I think that will make it render more nicely on https://pypi.python.org/pypi/osquery/0.1.1.

**Comment by thedrow** [comment]
Although the new PyPi should support markdown.

**Comment by theopolis** [comment]
@marpaia it is an RST: https://github.com/osquery/osquery-python/blob/master/README.rst there are several issues with PyPI's RST parsing. I attempted to fix the parsing: https://github.com/osquery/osquery-python/commit/0bdfa8be8d82931f1ae8119279decf0d06fbee72 and it was incomplete.
