### ISSUE TITLE
UI to interact with OSQuery

### ISSUE THREAD

**Issue by vasiqmz** [osquery/osquery-python#29]
I'm planning to create a UI, which provides an interactive way to query the OSQuery python in the backend and provide the result.

The idea is to create a Dynamic page that will allow the user to enter their query be it in SQL or in English syntax and execute the query in the back, this will provide much flexibility for the users.  

What is your comment on the idea ?

Awaiting for your reply.

**Comment by theopolis** [comment]
Hi @vasiqmz, that sounds great! Be sure to check out https://github.com/mwielgoszewski/doorman 

Perhaps you can contribute your ideas / plans to doorman instead of starting a new project?

**Comment by vasiqmz** [comment]
Thanks a lot. I was looking for similar project. Contributing sounds much better :)

**Comment by theopolis** [comment]
:+1:
