### ISSUE TITLE
Can two processes of  osquery use one extension socket?

### ISSUE THREAD

**Issue by foreversunyao** [osquery/osquery-python#30]
Hi ,

I face one problem, when I set up this new table, and start osqueryi by "osqueryi --extensions_socket=/var/osquery/shell.em" , and then I open a screen and use "python test.py --socket /var/osquery/osquery.em", it works. but when I open another screen and also run "python test.py --socket /var/osquery/osquery.em", I can not find any information about new table.

Is there anything I am wrong ?

**Comment by foreversunyao** [comment]
@theopolis Can you help me ?

**Comment by theopolis** [comment]
Hi @foreversunyao! In your test example the two extensions you're starting are **different** extensions right? Each extension has a name, there's an association between that name and the plugins (tables, config, logger, etc) it makes available to osquery. If you start two extensions with the same name, the second will fail to register.

Do you mind including your `osqueryi --verbose` debug output?

**Comment by foreversunyao** [comment]
Hi @theopolis , thanks for your help.
     We have only one extension, and what we want is we use one extension for our different request sessions.
     For example, we start an osquery by osqueryi --extensions_socket=/var/osquery/shell.em, and then register an extension by "python test.py --socket /var/osquery/shell.em", and the session of this osquery can request the "new table", but I want other session(new session request) can also request this "new table" , what should I do ?


This are the results:
I1121 14:58:35.369738 119876 init.cpp:364] osquery initialized [version=2.1.2]
I1121 14:58:35.369797 119876 extensions.cpp:351] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I1121 14:58:35.369812 119876 extensions.cpp:364] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I1121 14:58:35.369938 119876 init.cpp:606] Error reading config: config file does not exist: /etc/osquery/osquery.conf
I1121 14:58:35.369953 119878 interface.cpp:307] Extension manager service starting: /root/.osquery/shell.em
I1121 14:58:35.369972 119876 events.cpp:886] Error registering subscriber: socket_events: Subscriber disabled via configuration
Using a virtual database. Need help, type '.help'

**Comment by theopolis** [comment]
Your explanation should work, and that debug output is normal.
