### ISSUE TITLE
Can't use extensions in windows.

### ISSUE THREAD

**Issue by KennethVanMele** [osquery/osquery-python#54]
I started working on my custom table on windows but had to switch to Ubuntu due to pip issues. The extension works as intended on Ubuntu but when I tried on windows again it didn't work. I keep getting the following error: "Thrift message: TPipe::open ::CreateFile errored GLE=errono = 2". Nick Anderson on osquery.slack.com assured me this was a harmless info message. But when I go look in osquery.results.log it's empty whereas I use a built-in table like uptime, everything is a-ok. I even used the foobar_extension.ext on this git but no luck. I downgraded osquery to 2.11.2 as I started in that version but had since updated to 3.2.4, still no luck. Is this a known issue? Is it even an osquery-python issue (I'm only 70% sure)? Feel free to ask more information you need.

**Comment by muffins** [comment]
What version of the python extensions are you using? The only known version of osquery python extensions are 3.0.4
