### ISSUE TITLE
Python 3.5: Resource Warning 

### ISSUE THREAD

**Issue by fralau** [osquery/osquery-python#60]
I am using a SpawnInstance as an object within a class. Unfortunately

```python
self._instance = osquery.SpawnInstance()
...
self._instance.open()
r = self._instance.client.query(strSQL)
```

Apparently the SpawnInstance object leaves three resources open on exit and this triggers Python 3 warnings:
``` 
sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=7>
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=8>
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=10>
```

I tried to force a call to the `__del__` function of the instance, but this does not prevent the warning. Unfortunately this warning is difficult to mask, because the source is somewhere likely in a thread.

I am puzzled because the fowlling code does *not* trigger the ResourceWarning on exit:

```python
import osquery
instance = osquery.SpawnInstance()
instance.open()  # This may raise an exception
# Issues queries and call osquery Thrift APIs.
r = instance.client.query("select timestamp from time")
print(r)
```

Any idea what's happening?

**Comment by theopolis** [comment]
This is a legit issue, most likely caused by not closing mkstemp. I cannot see where that is closed.

**Comment by theopolis** [comment]
https://github.com/osquery/osquery-python/issues/66 seems related.

**Comment by theopolis** [comment]
This should be closed: https://github.com/osquery/osquery-python/blob/master/osquery/management.py#L74
