### ISSUE TITLE
thrift.transport.TTransport.TTransportException: Called read on non-open pipe

### ISSUE THREAD

**Issue by tbhaxor** [osquery/osquery-python#65]
**OS :** Windows 10

```py
import osquery

inst = osquery.SpawnInstance("C:\\ProgramData\\osquery\\osqueryi.exe")
inst.open()

cursor = inst.client

cursor.query("select name, version from programs;")
```

**Comment by 0x924** [comment]
Unfortunately i am getting the same error
but i am using another query

## code
```python
import osquery

if __name__ == "__main__":
     osq = osquery.SpawnInstance()
     osq.open()
     cursor.query("select * from users;")
```

## error
````bash
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    cursor.query("select name, version from programs;")
  File "C:\Users\malware-test\Anaconda3\lib\site-packages\osquery\extensions\ExtensionManager.py", line 181, in query
    self.send_query(sql)
  File "C:\Users\malware-test\Anaconda3\lib\site-packages\osquery\extensions\ExtensionManager.py", line 190, in send_query
    self._oprot.trans.flush()
  File "C:\Users\malware-test\Anaconda3\lib\site-packages\thrift\transport\TTransport.py", line 177, in flush
    self.__trans.write(out)
  File "C:\Users\malware-test\Anaconda3\lib\site-packages\osquery\TPipe.py", line 128, in write
    message='Called read on non-open pipe')
thrift.transport.TTransport.TTransportException: Called read on non-open pipe
```

**Comment by tbhaxor** [comment]
@0x924 lets wait what do they suggest

**Comment by prasanthbazz** [comment]
Hi ,
I'm getting the same error. Any idea how this can be fixed?

**Comment by prasanthbazz** [comment]
I believe the problem the OP faces is because he has provided the path to osquryi.exe instead of osqueryd. In my case, I faced the same problem as I gave wrong pipe name. (https://github.com/osquery/osquery-python#connect-to-an-existing-socket  - the comment in the code says to pass the pipe name in windows as \\.pipe\osquery.em which is wrong and should be \\.\pipe\osquery.em instead)

**Comment by VijayasaiVS** [comment]
> I believe the problem the OP faces is because he has provided the path to osquryi.exe instead of osqueryd. In my case, I faced the same problem as I gave the wrong pipe name. (https://github.com/osquery/osquery-python#connect-to-an-existing-socket - the comment in the code says to pass the pipe name in windows as \.pipe\osquery.em which is wrong and should be \.\pipe\osquery.em instead)

Thanks a lot! Me so dumb dumb......
