### ISSUE TITLE
osquery socket file leak

### ISSUE THREAD

**Issue by Addvilz** [osquery/osquery-python#75]
In `management.py` socket file is created on line 85 using mkstemp.

This file is NOT automatically removed, and remains forever in /tmp, so spawning osquery instances regularly results in many garbage tempfiles in /tmp. File deletion should be handled in `__del__`.

**Comment by Addvilz** [comment]
@theopolis do you want a PR here? I can prepare the change, unless you prefer otherwise.

**Comment by theopolis** [comment]
That would be fantastic! Yes please :)

**Comment by Addvilz** [comment]
There you go

**Comment by Addvilz** [comment]
@theopolis ...bump?

**Comment by theopolis** [comment]
Hey, thanks for the bump, I just reviewed and merged :)
