### ISSUE TITLE
new release request

### ISSUE THREAD

**Issue by mattf9** [osquery/osquery-python#97]
I recently had a small pull request approved and merged. Any chance that someone could create a release? Thanks!

**Comment by directionless** [comment]
I've made https://github.com/osquery/osquery-python/releases/tag/3.1.0 on github, but I don't really know python. So I don't know if there are other steps.

**Comment by mattf9** [comment]
Thanks! On github, I see your 3.1.0 tagged as "pre-release" and 3.0.6 as "Latest". Strangely, on [pypi.org](https://pypi.org/project/osquery/) I see 3.0.7 as being the latest (and I don't see a 3.0.7 tag on github)... so seems like there are some other steps here. Again, not urgent but maybe you could have a second look and/or reach out to the other maintainers to see what the process is.

**Comment by directionless** [comment]
I dug around a little. And then built some pypi release automation. It's still pretty janky. 

I see how `3.0.7` happened -- https://github.com/osquery/osquery-python/issues/100 captures it.

**Comment by directionless** [comment]
There are a lot of ways I think we could improve this. The packaging is may years old, and likely due for a refresh. There are no tests. Etc. I'm not a python developer though.
